"""empty message

Revision ID: 0b3fa2e55459
Revises: 87a598d296cb
Create Date: 2019-04-07 04:07:48.981739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3fa2e55459'
down_revision = '87a598d296cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tip', sa.Column('payment_request', sa.String(length=255), nullable=False))
    op.alter_column('tip', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tip', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tip', 'payment_request')
    # ### end Alembic commands ###
