"""Initial scaffolding

Revision ID: 8382b265cfd4
Revises: 
Create Date: 2019-04-06 19:15:57.806818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8382b265cfd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('macaroon', sa.String(length=1023), nullable=True),
    sa.Column('cert', sa.String(length=2047), nullable=True),
    sa.Column('node_url', sa.String(length=255), nullable=True),
    sa.Column('pubkey', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=63), nullable=False),
    sa.Column('site_id', sa.String(length=63), nullable=False),
    sa.Column('site_username', sa.String(length=63), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'site')
    )
    op.create_table('tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=63), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('repo', sa.String(length=63), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('rhash', sa.String(length=127), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'receiver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tip')
    op.drop_table('connection')
    op.drop_table('user')
    # ### end Alembic commands ###
